const std = @import("std");
pub const Lesson = struct { id: []const u8, title: []const u8, prerequisite: ?[]const u8, concept: []const u8, syntax: []const u8, mental_model: []const u8, examples: []const u8, corpus_evidence: []const u8, real_examples: []const u8, alternatives: []const u8, exercise: []const u8, feedback: []const u8, optional_depth: []const u8, intermediate_depth: []const u8, experienced_depth: []const u8, transfer_notes: []const u8, analyzer_limits: []const u8 };
const evidence = "Checked-in fixtures cover syntax recognition only, not prevalence. Run rgp analyze and rgp report for repository-specific counts; when no corpus is analyzed, no count is claimed.";
const depth = "Explore the Ruby API documentation and compare this construct with a small program of your own.";
const names = [_][]const u8{ "fundamentals", "conditionals", "loops", "arrays", "hashes", "enumerable", "methods", "blocks", "classes-modules", "exceptions", "pattern_matching", "metaprogramming", "files_and_dependencies", "concurrency", "testing", "real_world_ruby_idioms" };
const titles = [_][]const u8{ "Ruby fundamentals", "Conditionals", "Loops and iteration", "Arrays", "Hashes", "Enumerable", "Methods", "Blocks", "Classes and modules", "Exceptions", "Pattern matching", "Metaprogramming", "Files and dependencies", "Concurrency", "Testing and verification", "Real-world Ruby idioms" };
const prereqs = [_]?[]const u8{ null, "fundamentals", "conditionals", "loops", "arrays", "hashes", "enumerable", "methods", "blocks", "classes-modules", "exceptions", "pattern_matching", "metaprogramming", "blocks", "exceptions", "testing" };
const concepts = [_][]const u8{ "Values have types, names point at values, and expressions return values.", "Conditionals choose an expression by truthiness; only false and nil are falsey.", "Iteration repeats work; collections commonly yield items to a block.", "An Array is an ordered, zero-indexed collection.", "A Hash maps keys to values for named options and records.", "Enumerable gives collections a vocabulary: map, select, reduce, and find.", "Methods package behavior behind names, parameters, and return values.", "A block is behavior passed to a method and may close over surrounding names.", "Classes define object shape and behavior; modules package behavior or names.", "Exceptions signal failed operations; rescue expected failures and ensure cleanup." };
const syntax = [_][]const u8{ "name = expression; puts \"Hello #{name}\"", "if/elsif/else/end; unless/end; condition ? a : b", "items.each { |item| ... }; while condition ... end; 3.times { ... }", "items = [1, 2]; items[0]; items << 3", "user = { name: \"Ada\" }; user[:name]; user.fetch(:name)", "numbers.map { |n| n * 2 }; values.reduce(0, :+)", "def greet(name); \"Hello #{name}\"; end", "items.each do |item| ... end; yield; &work", "class User; attr_reader :name; end; module Loggable; end", "begin/rescue/ensure/end; raise message" };
const models = [_][]const u8{ "Read Ruby as expressions: assignment gives a name a new reference.", "A conditional is a fork that produces a value.", "The collection owns traversal and the block handles one item.", "Picture an array as numbered shelves; index 0 is first.", "A hash is a labeled lookup table; missing and nil are distinct.", "Describe the result instead of managing loop state.", "A method is a contract: inputs in, result out.", "The method owns when to invoke behavior; the caller supplies what to do.", "Use a class for modeled objects; a module for a shared capability or namespace.", "Handle exceptions where recovery or useful context is possible." };
const examples = [_][]const u8{ "name = \"Ada\"; puts \"Hello, #{name}!\"", "message = if age >= 18; \"adult\"; else; \"child\"; end", "total = 0; [2,4,6].each { |n| total += n }", "languages = [\"Ruby\", \"Zig\"]; languages << \"SQL\"", "scores = { ada: 10 }; scores[:ada] += 1", "[1,2,3,4].select(&:even?).map { |n| n * 2 }", "def percentage(part, whole); (part.to_f / whole * 100).round; end", "def twice; yield; yield; end; twice { puts \"Ruby\" }", "class Counter; def initialize; @n = 0; end; end", "def parse_count(text); Integer(text); rescue ArgumentError; nil; end" };
const real = [_][]const u8{ "CLI scripts combine ARGV, interpolation, and puts to make reports.", "Validation uses guards; dispatch commonly uses case.", "Batch jobs use each; retry polling uses while with limits.", "ARGV and ordered API response items are common arrays.", "Option hashes carry configuration and JSON-like hashes carry records.", "Reports map records, select valid rows, and reduce totals.", "Libraries expose methods that validate, delegate, and return domain values.", "File and transaction helpers yield work and ensure cleanup.", "Domain classes own invariants; modules supply logging or serialization.", "File/network boundaries rescue documented failures and add context." };
const alternatives = [_][]const u8{ "Use p for debugging and puts for human-readable lines.", "Use guard clauses, case for alternatives, or a hash when the mapping is data.", "Prefer each/times for collections; use for when variable leakage is intentional.", "Choose Hash for keys, Set for uniqueness, Enumerator for lazy values.", "Use Struct/class for stable shape with behavior; Array when order is primary.", "Use each for side effects; use a plain loop for several mutable states.", "Use a local for one calculation, callable for behavior as data, class for state.", "Use a named method for stable behavior, lambda for strict callable behavior.", "Prefer composition when behavior belongs to a collaborator.", "Use conditionals for expected absence; never rescue Exception broadly." };
const exercises = [_][]const u8{ "Name a person and score, then print NAME scored SCORE.", "Return adult for age >= 18 and child otherwise; add role cases.", "Print even numbers with each, then write a while version.", "Build four tasks, print the first, and print 1-based positions.", "Create a book hash and safely read an optional ISBN.", "Select active users, map names, and reduce their points.", "Write summarize(numbers) returning count, min, max, and total.", "Implement with_banner(title) that prints, yields, then prints.", "Create Counter with increment/value and a reset module.", "Parse integer text with a fallback without hiding unrelated errors." };
const feedback = [_][]const u8{ "Check assignment order, interpolation, and one-line output.", "Test boundary values 17 and 18 and decide how nil behaves.", "Ensure termination, complete coverage, and no off-by-one gap.", "Confirm index 0 and that append changes the original array.", "Use consistent keys and distinguish key? from a truthy value.", "Check select/map return arrays and reduce returns one value.", "Test normal and edge cases and return data rather than print it.", "Ensure the block is invoked once and ownership is clear.", "Two instances must have independent state; hide instance variables.", "Test valid, invalid, and unrelated exceptions; rescue only conversion errors." };
const advanced_concepts = [_][]const u8{ "Patterns destructure values and make shape-based branching explicit.", "Metaprogramming generates behavior at runtime; keep the resulting API discoverable.", "Ruby loads code at runtime while Bundler records a reproducible dependency graph.", "Threads, fibers, queues, and processes differ in scheduling and isolation.", "Tests specify observable behavior; a green suite is not proof of everything.", "Real-world idioms combine language features with framework conventions; understand the reason before copying the shape." };
const advanced_syntax = [_][]const u8{ "case value; in { name: }; ...; end", "define_method(:name) { ... }; obj.public_send(:name)", "require \"json\"; require_relative \"support\"", "Thread.new { ... }; queue << value; queue.pop", "class UserTest < Minitest::Test; assert_equal ...; end", "records = rows.filter_map { |row| normalize(row) }; value = config.fetch(:value, default)" };
const advanced_models = [_][]const u8{ "A pattern is a checked shape plus bindings.", "Treat generated methods as code with a lifecycle: define, call, inspect, remove.", "Separate source lookup, loading, and version resolution.", "Separate coordination from work; shared state still needs protection.", "A test is an executable claim with controlled inputs and scope.", "An idiom is a reviewed solution to a recurring context, not a popularity contest; make its assumptions visible." };
const advanced_examples = [_][]const u8{ "case event; in { type: \"push\", ref: }; ref; else; nil; end", "class Value; define_method(:twice) { @n * 2 }; end", "require_relative \"lib/formatter\"; JSON.parse(File.read(path))", "work = Queue.new; worker = Thread.new { work.pop.call }; worker.join", "require \"minitest/autorun\"; assert_equal 2, add(1, 1)", "File.open(path) { |file| file.each_line.lazy.map(&:chomp).first(10) }" };
const advanced_real = [_][]const u8{ "Parsers and event routers use patterns when input shape is the decision.", "Framework DSLs use metaprogramming, but public behavior stays testable.", "A gem lib/ layout, require paths, Gemfile, and lockfile form its contract.", "Servers use threads or processes plus queues; fibers are cooperative.", "Minitest and RSpec organize assertions and integration boundaries differently.", "Rails, Hanami, and command-line Ruby emphasize different conventions; compare repository evidence before generalizing." };
const advanced_alternatives = [_][]const u8{ "Use ordinary case or guards when shape is not the decision.", "Prefer explicit methods when runtime generation adds indirection.", "Use require_relative for local source and Bundler for dependencies.", "Use a process for isolation, a queue for ownership, and a mutex for a small critical section; measure first.", "Test behavior at the narrowest useful boundary.", "Prefer the clearest form that preserves the framework contract; an idiom is not automatically correct." };
const advanced_exercises = [_][]const u8{ "Match an event hash by type and bind its ref; include a non-match.", "Define one method from data and explain how to test and remove it.", "Split a library into lib/ and require it without loading it twice.", "Build a producer/consumer example with Queue and explain ownership.", "Write a unit test for a formatter and an integration test for its file boundary.", "Refactor a small routine into an idiom, then record the semantic and performance trade-offs and one case where the original is clearer." };
const advanced_feedback = [_][]const u8{ "Test matching, non-matching, missing-key, and extra-key inputs.", "Check visibility, lookup, and failure behavior; syntax is not runtime proof.", "Verify load paths, version constraints, and the lockfile; stay offline.", "Test shutdown and failure paths; do not choose by frequency.", "Keep setup deterministic and state what is not covered.", "Check behavior, allocation, framework convention, and edge cases; explain why frequency alone is insufficient." };
const advanced_limits = [_][]const u8{ "Pattern binding, exhaustiveness, and prevalence are unsupported; fixtures establish syntax only.", "Metaprogramming is not measured; runtime generation requires a probe or corpus evidence.", "Dependency-file measurements are unsupported; cite project files for claims.", "No scheduler, safety, contention, or timing claim is made; use tested probes.", "No test runner or assertion outcome is executed; presence is not coverage proof.", "Idiom detection is evidence-backed but corpus-scoped; a detected shape does not prove intent, correctness, or best performance." };
const generic_intermediate = "Compare with an explicit implementation, then measure or test the claimed trade-off.";
const generic_experienced = "Review API, compatibility, performance, memory, and failure trade-offs; frequency is not correctness.";
const generic_transfer = "For developers from another language, name the closest construct and record where Ruby semantics differ.";
const generic_limits = "The offline analyzer observes syntax and checked-in evidence; it does not execute Ruby or infer runtime behavior.";
pub const lessons = blk: {
    var out: [16]Lesson = undefined;
    for (names, 0..) |id, i| out[i] = .{ .id = id, .title = titles[i], .prerequisite = prereqs[i], .concept = if (i < 10) concepts[i] else advanced_concepts[i - 10], .syntax = if (i < 10) syntax[i] else advanced_syntax[i - 10], .mental_model = if (i < 10) models[i] else advanced_models[i - 10], .examples = if (i < 10) examples[i] else advanced_examples[i - 10], .corpus_evidence = if (i == 0) "No analyzed corpus is required; this offline lesson does not invent counts." else evidence, .real_examples = if (i < 10) real[i] else advanced_real[i - 10], .alternatives = if (i < 10) alternatives[i] else advanced_alternatives[i - 10], .exercise = if (i < 10) exercises[i] else advanced_exercises[i - 10], .feedback = if (i < 10) feedback[i] else advanced_feedback[i - 10], .optional_depth = depth, .intermediate_depth = generic_intermediate, .experienced_depth = generic_experienced, .transfer_notes = generic_transfer, .analyzer_limits = if (i < 10) generic_limits else advanced_limits[i - 10] };
    break :blk out;
};
pub fn find(id: []const u8) ?Lesson {
    for (lessons) |l| if (std.mem.eql(u8, l.id, id)) return l;
    if (std.mem.eql(u8, id, "enumerables")) return lessons[5];
    if (std.mem.eql(u8, id, "classes_modules") or std.mem.eql(u8, id, "oop")) return lessons[8];
    return null;
}

test "extended curriculum covers senior sections and evidence boundaries" {
    try std.testing.expectEqual(@as(usize, 16), lessons.len);
    try std.testing.expectEqualStrings("pattern_matching", lessons[11].prerequisite.?);
    try std.testing.expect(std.mem.indexOf(u8, lessons[10].analyzer_limits, "unsupported") != null);
    try std.testing.expect(std.mem.indexOf(u8, lessons[11].experienced_depth, "performance") != null);
    try std.testing.expect(std.mem.indexOf(u8, lessons[15].exercise, "trade-offs") != null);
}
