const std = @import("std");
pub const Lesson = struct { id: []const u8, title: []const u8, prerequisite: ?[]const u8, concept: []const u8, syntax: []const u8, mental_model: []const u8, examples: []const u8, corpus_evidence: []const u8, real_examples: []const u8, alternatives: []const u8, exercise: []const u8, feedback: []const u8, optional_depth: []const u8 };
const evidence = "Checked-in fixtures cover syntax recognition only, not prevalence. Run rgp analyze and rgp report for repository-specific counts; when no corpus is analyzed, no count is claimed.";
const depth = "Explore the Ruby API documentation and compare this construct with a small program of your own.";
const names = [_][]const u8{ "fundamentals", "conditionals", "loops", "arrays", "hashes", "enumerable", "methods", "blocks", "classes-modules", "exceptions" };
const titles = [_][]const u8{ "Ruby fundamentals", "Conditionals", "Loops and iteration", "Arrays", "Hashes", "Enumerable", "Methods", "Blocks", "Classes and modules", "Exceptions" };
const prereqs = [_]?[]const u8{ null, "fundamentals", "conditionals", "loops", "arrays", "hashes", "enumerable", "methods", "blocks", "classes-modules" };
const concepts = [_][]const u8{ "Values have types, names point at values, and expressions return values.", "Conditionals choose an expression by truthiness; only false and nil are falsey.", "Iteration repeats work; collections commonly yield items to a block.", "An Array is an ordered, zero-indexed collection.", "A Hash maps keys to values for named options and records.", "Enumerable gives collections a vocabulary: map, select, reduce, and find.", "Methods package behavior behind names, parameters, and return values.", "A block is behavior passed to a method and may close over surrounding names.", "Classes define object shape and behavior; modules package behavior or names.", "Exceptions signal failed operations; rescue expected failures and ensure cleanup." };
const syntax = [_][]const u8{ "name = expression; puts \"Hello #{name}\"", "if/elsif/else/end; unless/end; condition ? a : b", "items.each { |item| ... }; while condition ... end; 3.times { ... }", "items = [1, 2]; items[0]; items << 3", "user = { name: \"Ada\" }; user[:name]; user.fetch(:name)", "numbers.map { |n| n * 2 }; values.reduce(0, :+)", "def greet(name); \"Hello #{name}\"; end", "items.each do |item| ... end; yield; &work", "class User; attr_reader :name; end; module Loggable; end", "begin/rescue/ensure/end; raise message" };
const models = [_][]const u8{ "Read Ruby as expressions: assignment gives a name a new reference.", "A conditional is a fork that produces a value.", "The collection owns traversal and the block handles one item.", "Picture an array as numbered shelves; index 0 is first.", "A hash is a labeled lookup table; missing and nil are distinct.", "Describe the result instead of managing loop state.", "A method is a contract: inputs in, result out.", "The method owns when to invoke behavior; the caller supplies what to do.", "Use a class for modeled objects; a module for a shared capability or namespace.", "Handle exceptions where recovery or useful context is possible." };
const examples = [_][]const u8{ "name = \"Ada\"; puts \"Hello, #{name}!\"", "message = if age >= 18; \"adult\"; else; \"child\"; end", "total = 0; [2,4,6].each { |n| total += n }", "languages = [\"Ruby\", \"Zig\"]; languages << \"SQL\"", "scores = { ada: 10 }; scores[:ada] += 1", "[1,2,3,4].select(&:even?).map { |n| n * 2 }", "def percentage(part, whole); (part.to_f / whole * 100).round; end", "def twice; yield; yield; end; twice { puts \"Ruby\" }", "class Counter; def initialize; @n = 0; end; end", "def parse_count(text); Integer(text); rescue ArgumentError; nil; end" };
const real = [_][]const u8{ "CLI scripts combine ARGV, interpolation, and puts to make reports.", "Validation uses guards; dispatch commonly uses case.", "Batch jobs use each; retry polling uses while with limits.", "ARGV and ordered API response items are common arrays.", "Option hashes carry configuration and JSON-like hashes carry records.", "Reports map records, select valid rows, and reduce totals.", "Libraries expose methods that validate, delegate, and return domain values.", "File and transaction helpers yield work and ensure cleanup.", "Domain classes own invariants; modules supply logging or serialization.", "File/network boundaries rescue documented failures and add context." };
const alternatives = [_][]const u8{ "Use p for debugging and puts for human-readable lines.", "Use guard clauses, case for alternatives, or a hash when the mapping is data.", "Prefer each/times for collections; use for when variable leakage is intentional.", "Choose Hash for keys, Set for uniqueness, Enumerator for lazy values.", "Use Struct/class for stable shape with behavior; Array when order is primary.", "Use each for side effects; use a plain loop for several mutable states.", "Use a local for one calculation, callable for behavior as data, class for state.", "Use a named method for stable behavior, lambda for strict callable behavior.", "Prefer composition when behavior belongs to a collaborator.", "Use conditionals for expected absence; never rescue Exception broadly." };
const exercises = [_][]const u8{ "Name a person and score, then print NAME scored SCORE.", "Return adult for age >= 18 and child otherwise; add role cases.", "Print even numbers with each, then write a while version.", "Build four tasks, print the first, and print 1-based positions.", "Create a book hash and safely read an optional ISBN.", "Select active users, map names, and reduce their points.", "Write summarize(numbers) returning count, min, max, and total.", "Implement with_banner(title) that prints, yields, then prints.", "Create Counter with increment/value and a reset module.", "Parse integer text with a fallback without hiding unrelated errors." };
const feedback = [_][]const u8{ "Check assignment order, interpolation, and one-line output.", "Test boundary values 17 and 18 and decide how nil behaves.", "Ensure termination, complete coverage, and no off-by-one gap.", "Confirm index 0 and that append changes the original array.", "Use consistent keys and distinguish key? from a truthy value.", "Check select/map return arrays and reduce returns one value.", "Test normal and edge cases and return data rather than print it.", "Ensure the block is invoked once and ownership is clear.", "Two instances must have independent state; hide instance variables.", "Test valid, invalid, and unrelated exceptions; rescue only conversion errors." };
pub const lessons = blk: {
    var out: [10]Lesson = undefined;
    for (names, 0..) |id, i| out[i] = .{ .id = id, .title = titles[i], .prerequisite = prereqs[i], .concept = concepts[i], .syntax = syntax[i], .mental_model = models[i], .examples = examples[i], .corpus_evidence = if (i == 0) "No analyzed corpus is required; this offline lesson does not invent counts." else evidence, .real_examples = real[i], .alternatives = alternatives[i], .exercise = exercises[i], .feedback = feedback[i], .optional_depth = depth };
    break :blk out;
};
pub fn find(id: []const u8) ?Lesson {
    for (lessons) |l| if (std.mem.eql(u8, l.id, id)) return l;
    if (std.mem.eql(u8, id, "enumerables")) return lessons[5];
    if (std.mem.eql(u8, id, "classes_modules") or std.mem.eql(u8, id, "oop")) return lessons[8];
    return null;
}
