/* Initial web adapter. Domain facts remain in the versioned RGP gateway. */
const endpoint = globalThis.RGP_API_ENDPOINT || "/api/tools";
const app = document.querySelector("#app");
const provenance = document.querySelector("[data-provenance]");
const nav = [...document.querySelectorAll("[data-route]")];
const state = { learnerId: Number(globalThis.RGP_LEARNER_ID || 1), lesson: null, exercise: null };

async function call(tool, input) {
  const response = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ tool: `rgp.${tool}`, input: JSON.stringify(input), request_id: `web-${Date.now()}` }) });
  if (!response.ok) throw new Error(`Gateway returned HTTP ${response.status}`);
  const envelope = await response.json();
  if (!envelope.ok) throw new Error(envelope.error_message || envelope.error_code || "The gateway rejected the request");
  const output = typeof envelope.output === "string" ? JSON.parse(envelope.output) : envelope.output;
  provenance.textContent = `${envelope.provenance?.evidence_authority || "RGP"} · deterministic response · ${envelope.result_id || "unversioned"}`;
  return output;
}

function shell(title, intro, content) { return `<section class="hero"><p class="eyebrow">RGP / ${title}</p><h1>${title}</h1><p>${intro}</p></section>${content}`; }
function loading() { app.innerHTML = '<div class="loading" aria-live="polite">Loading…</div>'; }
function failure(error) { app.innerHTML = `<div class="error" role="alert"><h2>We couldn’t load this view</h2><p>${escapeHtml(error.message)}</p><button class="secondary" data-retry>Try again</button></div>`; document.querySelector("[data-retry]").onclick = render; }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])); }
function list(items, render) { return items?.length ? `<div class="grid">${items.map(render).join("")}</div>` : '<div class="empty">No evidence is available yet.</div>'; }

async function learn() {
  const ids = ["fundamentals", "conditionals", "loops", "arrays", "hashes", "enumerable", "methods", "blocks", "classes-modules", "exceptions"];
  return shell("Learn", "Follow a structured path from Ruby syntax to the decisions experienced Rubyists make.", list(ids, id => `<article class="card interactive"><button class="secondary" data-lesson="${id}"><span class="tag">Lesson</span><h3>${id.replaceAll("_", " ")}</h3><p>Open the lesson and its evidence-backed exercise.</p></button></article>`));
}
async function explore(topic) { if (topic) { const report = await call("get_topic", { id: topic }); return shell("Explore / " + topic.replaceAll("-", " "), "A report from the analyzed corpus, with deterministic facts and source provenance.", `<div class="card"><h2>Report</h2><pre>${escapeHtml(JSON.stringify(report, null, 2))}</pre><p class="muted">Use Corpus to inspect cited source examples for individual constructs.</p></div>`); } return shell("Explore", "Drill into topics, compare constructs, and inspect the source evidence behind each observation.", list(["collections", "conditionals", "loops-and-iteration"], topicId => `<article class="card interactive"><button class="secondary" data-topic="${topicId}"><span class="tag">Topic</span><h3>${topicId.replaceAll("-", " ")}</h3><p>View reports and cited examples.</p></button></article>`)); }
async function practice() { const exercise = await call("get_exercise", { id: "collections.map-names" }); state.exercise = exercise; return shell("Practice", "Try a reviewed exercise. The offline validator checks syntax and supported static shape; it does not execute Ruby.", `<article class="card"><span class="tag">${escapeHtml(exercise.competency)}</span><h2>${escapeHtml(exercise.title)}</h2><p>${escapeHtml(exercise.prompt)}</p><form id="exercise-form" class="form-grid"><label>Your Ruby solution<textarea name="source" required aria-describedby="exercise-help"></textarea></label><p id="exercise-help" class="muted">Your submission is sent to the deterministic RGP gateway.</p><button>Submit exercise</button></form><div id="exercise-result" aria-live="polite"></div></article>`); }
async function explain() { return shell("Explain", "Paste a Ruby snippet to get a syntax-grounded explanation request. Source stays under the configured API boundary.", `<form id="explain-form" class="card form-grid"><label>Ruby source<textarea name="source" required placeholder="users.map { |user| user.name }"></textarea></label><button>Request explanation</button><div id="explain-result" aria-live="polite"></div></form>`); }
async function corpus() { const examples = await call("find_examples", { construct: "map", limit: 20 }); return shell("Corpus", "Inspect examples from the analyzed corpus with source and project provenance preserved.", `<div class="card"><h2>map examples</h2>${list(examples.examples || examples.items, item => `<article class="evidence"><h3>${escapeHtml(item.project || item.source || "Corpus example")}</h3><pre>${escapeHtml(item.source || item.text || JSON.stringify(item))}</pre><p class="muted">${escapeHtml(item.path || item.provenance || "Provenance returned by RGP")}</p></article>`)}</div>`); }
async function progress() { const data = await call("get_progress", { learner_id: state.learnerId }); return shell("Progress", "See what you have encountered, practiced, and demonstrated. Progress is read from learner storage.", `<div class="card"><h2>Learner ${escapeHtml(data.learner_id)}</h2>${list(data.competencies, item => `<article class="evidence"><h3>${escapeHtml(item.key)}</h3><p>Exposure ${item.exposure} · Practice ${item.practice} · Demonstrated ${item.demonstrated}</p></article>`)}</div><div class="card"><h2>Completed lessons</h2>${data.completed_lessons?.length ? `<p>${data.completed_lessons.map(escapeHtml).join(" · ")}</p>` : '<p class="empty">Complete a lesson to see it here.</p>'}</div>`); }

async function render() {
  const route = (location.hash.slice(1) || "learn").split("/");
  const page = route[0]; nav.forEach(link => link.setAttribute("aria-current", link.dataset.route === page ? "page" : "false")); loading();
  try { app.innerHTML = await (page === "explore" ? explore(route[1]) : ({ learn, practice, explain, corpus, progress }[page] || learn))(); bind(); app.focus({ preventScroll: true }); }
  catch (error) { failure(error); }
}
function bind() {
  document.querySelectorAll("[data-lesson]").forEach(button => button.onclick = async () => { try { const lesson = await call("get_lesson", { id: button.dataset.lesson }); app.innerHTML = shell(escapeHtml(lesson.title), escapeHtml(lesson.concept), `<div class="split"><article class="card"><h2>Lesson</h2><p>${escapeHtml(lesson.mental_model || lesson.syntax || lesson.exercise)}</p><button data-complete="${lesson.id}">Mark complete</button></article><article class="card"><h2>Evidence & limits</h2><p>${escapeHtml(lesson.corpus_evidence || lesson.analyzer_limits || "No additional evidence supplied.")}</p></article></div>`); bind(); } catch (error) { failure(error); } });
  document.querySelectorAll("[data-topic]").forEach(button => button.onclick = () => { location.hash = "explore/" + button.dataset.topic; });
  document.querySelectorAll("[data-complete]").forEach(button => button.onclick = async () => { button.disabled = true; button.textContent = "Saving…"; try { await call("record_progress", { learner_id: state.learnerId, lesson_id: button.dataset.complete, status: "completed", position: 1 }); button.textContent = "Completed"; } catch (error) { button.disabled = false; button.textContent = "Mark complete"; failure(error); } });
  const form = document.querySelector("#exercise-form"); if (form) form.onsubmit = async event => { event.preventDefault(); const target = document.querySelector("#exercise-result"); target.textContent = "Checking…"; try { const source = new FormData(form).get("source"); const result = await call("submit_exercise", { exercise_id: state.exercise.id, learner_id: state.learnerId, source, source_sha256: "client-submission" }); target.innerHTML = `<div class="evidence"><h3>${escapeHtml(result.outcome)}</h3><p>Attempt ${escapeHtml(result.attempt_id)} recorded. Evidence authority: RGP.</p></div>`; } catch (error) { target.innerHTML = `<div class="error" role="alert">${escapeHtml(error.message)}</div>`; } };
  const explainForm = document.querySelector("#explain-form"); if (explainForm) explainForm.onsubmit = async event => { event.preventDefault(); const target = document.querySelector("#explain-result"); target.textContent = "Parsing and requesting explanation…"; try { const data = new FormData(explainForm); const source = data.get("source"); const parsed = await call("parse_file", { path: "<web-input>", source }); if (parsed.success === false) { target.innerHTML = `<div class="error" role="alert"><h3>Syntax diagnostics</h3><pre>${escapeHtml(JSON.stringify(parsed, null, 2))}</pre></div>`; return; } const response = await fetch(globalThis.RGP_EXPLAIN_ENDPOINT || "/api/explain", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ source, level: data.get("level") }) }); if (!response.ok) throw new Error(`Explanation adapter returned HTTP ${response.status}`); const explanation = await response.json(); target.innerHTML = `<div class="evidence"><h3>Explanation</h3><p>${escapeHtml(explanation.explanation || explanation.output || "The adapter returned no explanation.")}</p><p class="muted">Syntax facts were checked by RGP before this explanation was requested.</p></div>`; } catch (error) { target.innerHTML = `<div class="error" role="alert">${escapeHtml(error.message)}</div>`; } };
}
addEventListener("hashchange", render); render();
